#!/bin/bash


_get_zlink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "sbb_b" ]]
    then
        echo "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=" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "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=" | base64 -d
    
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "sbb_b" ]]
    then
        rlink=`echo "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" | base64 -d`
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        rlink=`echo "${UPSTREAM_REPO}"`
    else
        rlink=`echo "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" | base64 -d`
    fi
    echo "$rlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_catpackgit() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/Alapath1/zthon"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_catgit() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "main"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_start_bot () {
    local zippath
    zippath="ZedThon1.zip"
    echo "⌭ جاري تنزيل اكواد السورس ⌭"
    wget -q $(_get_zlink) -O "$zippath"
    echo "⌭ تفريغ البيانات ⌭"
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "⌭ تـم التفريـغ ⌭"
    echo "⌭ يتم التنظيف ⌭"
    rm -rf "$zippath"
    _run_catpackgit
    cd $CATPATH
    _run_catgit
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "⌭ جـاري بـدء تنصيـب زدثـــون ⌭ "
    echo "

    "
    python3 -m zthon
}

_start_bot
